[tool]
[tool.poetry]
name = "worldengine"
version = "0.0.0"
description = ""
authors = ["Samuel Bishop <sam@psyx.co>"]

[tool.poetry.dependencies]
python = "^3.7"
argparse = "==1.2.1"
noise = ">=1.2.2"
numpy = "1.14.6"
protobuf = "==3.0.0a3"
pyplatec = "==1.4.0"
pypng = ">=0.0.18"
six = ">=1.16.0"
